### ISSUE TITLE
Example project throws compile errors

### ISSUE THREAD

**Issue by ghost** [CatalystApps/Cocos2dxGAFPlayer#19]
I got a copy of this git repository and tried to run the Example.xcodeproject.
Initially i got a "cocos2d.h not found" error and noticed that the cocos_lobs.xcodeproject was missing so i included the project from my local copy of the cocos2dx library (v3.2). I tried running the build with that but consistently got compile time errors...not sure whats going wrong here!

**Comment by Teivaz** [comment]
Make sure that GAFPlayer is in cocos2d-x/external/ folder of your cocos library.

**Comment by xmarklabs** [comment]
That worked. Thank you!
