### ISSUE TITLE
CMake config lack c++11 flags

### ISSUE THREAD

**Issue by zilongshanren** [CatalystApps/Cocos2dxGAFPlayer#55]
The gaf v4 branch can't build properly. you might need to add the following cxx flags:

```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-exceptions -std=c++11 -Wno-deprecated-declarations -Wno-reorder")

if(IOS OR MACOX)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
endif()
```

**Comment by SmartCat** [comment]
Thank you!
Flags was added to gaf_4_develop branch

**Comment by zilongshanren** [comment]
@SmartCat 
Oops, The if(IOS OR MACOX) is wrong in my comment.
It should be if(MACOSX OR APPLE).
Sorry for the misleading information here. 

could you please fix it ?

BTW, your cmake configuration seems doesn't support iOS, right?
