### ISSUE TITLE
Moving the "GAFAnimatedObject" produces a flicker.

### ISSUE THREAD

**Issue by Naii07** [CatalystApps/Cocos2dxGAFPlayer#56]
firstly, I create a GAFAnimatedObject and play it.

GAFAnimatedObject \* obj;
......
obj->play();

Then, I call setPosition.
Beacuse I want to move it while animation playing.

obj->setPosition(...);

I see the animation flickering on the screen, after that.

Here is my code.
http://7tsyzg.com1.z0.glb.clouddn.com/Code.rar
You can create a HelloWorld project and copy files into it.
PS: I come from China. I am not very sure if the URL is available to you.

Thank you.

**Comment by SmartCat** [comment]
Hello!
For quickfix you can check GAFAnimatedObject::rearrangeSubobject method. And uncomment line
static_cast< GAFAnimatedObject\* >(child)->_transformUpdated = true;
We will return to testing this issue tommorow and we'll commit fix after all.

**Comment by Naii07** [comment]
I uncomment static_cast< GAFAnimatedObject\* >(child)->_transformUpdated = true;
It works.
Thank for you help

**Comment by SmartCat** [comment]
Hello!
Same fix was commited
