### ISSUE TITLE
get gaf file's reference files

### ISSUE THREAD

**Issue by geron-cn** [CatalystApps/Cocos2dxGAFPlayer#59]
Can you give a function `static std::vector<std::string> GAFFile::getReferenceFiles(std::string gafFilePath)` to get all files gaf refers (including audios images fonts) with out init any glview or cocos2d ?
so we can check whether the gaf is legal.

thank you.

**Comment by SmartCat** [comment]
Hello,
We'll investigate this and return with solution tomorrow.

Regards,
Dmitry

**Comment by geron-cn** [comment]
My suggestion is parse the .gaf binary file directly to get its reference files.

Regards.

**Comment by geron-cn** [comment]
completed in  pr #60
