### ISSUE TITLE
GL call increase endless

### ISSUE THREAD

**Issue by TerranTian** [CatalystApps/Cocos2dxGAFPlayer#65]

**Comment by SmartCat** [comment]
Hi!
Can you provide example code and gaf/png files ?

**Comment by TerranTian** [comment]
here is my test code:
    local asset = gaf.GAFAsset:create("res/gaf/peacock_feb3_natasha/peacock_feb3_natasha.gaf");
    local node =  asset:createObjectAndRun(true);
    node:setPosition(cc.p(100,600))
    scene:addChild(node);

The status values of cocos2d-x just increase endless, I've test these problem both in release-gaf-4 and release-gaf-5.
![image](https://cloud.githubusercontent.com/assets/2083024/14141883/9a37a4ce-f6b4-11e5-8ea3-c68b2e15513d.png)

here is the screenshot after serval minutes：
![Uploading 8DABB0CE-1B4E-4555-83CA-1606544D00A0.png…]()

**Comment by TerranTian** [comment]
![Uploading 8DABB0CE-1B4E-4555-83CA-1606544D00A0.png…]()

**Comment by SmartCat** [comment]
Hi!
I've just checked on new clean project and I can't reproduce your issue

> function MainScene:onCreate()
>     -- add HelloWorld label
>     cc.Label:createWithSystemFont("Hello World", "Arial", 40)
>         :move(display.cx, display.cy + 200)
>         :addTo(self)
>     local asset = gaf.GAFAsset:create("biggreen/biggreen.gaf")
>     local gaf_obj = asset:createObjectAndRun(true)
>     gaf_obj:move(display.cx / 2, display.cy)
>     gaf_obj:addTo(self)
> end

![image](https://cloud.githubusercontent.com/assets/731945/14145755/ae00d79e-f69d-11e5-90c6-db16ff981083.png)
